"""empty message

Revision ID: 5e0f92cb416b
Revises: 
Create Date: 2021-05-28 16:36:38.698686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0f92cb416b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=6), nullable=True),
    sa.Column('is_done', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint("priority IN ('LOW', 'MEDIUM', 'HIGH')", name='priority'),
    sa.CheckConstraint('is_done IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
